// <auto-generated />
using Administration.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Administration.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20241001111042_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Administration.Models.Client", b =>
                {
                    b.Property<int>("ID_Client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Client"));

                    b.HasKey("ID_Client");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Administration.Models.Employe", b =>
                {
                    b.Property<int>("ID_Employe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Employe"));

                    b.HasKey("ID_Employe");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("Administration.Models.Fournisseur", b =>
                {
                    b.Property<int>("ID_Fourinisseur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Fourinisseur"));

                    b.HasKey("ID_Fourinisseur");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("Administration.Models.Service", b =>
                {
                    b.Property<int>("ID_Service")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Service"));

                    b.Property<string>("Designation_Service")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrixHT")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("PrixTTC")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("TVA")
                        .HasColumnType("int");

                    b.HasKey("ID_Service");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Administration.Models.Societe", b =>
                {
                    b.Property<int>("ID_Societe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Societe"));

                    b.HasKey("ID_Societe");

                    b.ToTable("Societes");
                });
#pragma warning restore 612, 618
        }
    }
}
